### ISSUE TITLE
Search an equivalent

### ISSUE THREAD

**Issue by anresa** [anresa/capstone-project#1]
## Value Proposition

**As a** user
**I need** to find a product's equivalent from one country to another
**to be able to** use it

## Description

<img width="450" alt="Search issue picture" src="https://user-images.githubusercontent.com/106099037/179221562-38afca0c-60b5-4ebd-809f-c620f22f8ffd.png">

## Acceptance Criteria

- [x] I can type my desired product into a search bar
- [x] After I click the submit button (Mismo!) a product card replaces the search section
- [x] I can find each equivalent with its own card
- [x] The product name is included on the card
- [x] The product picture is included on the card
- [x] When I click the back button, I exit out of the card and the search section reappears in its place

## Tasks

(for developers team)

- [x] Create db.js with equivalents
- [x] Searchbar
- [x] Submit button (Mismo!)
- [x] Back button
- [x] Equivalent cards
- [x] Styling
