### ISSUE TITLE
Filter by country

### ISSUE THREAD

**Issue by anresa** [anresa/capstone-project#2]
## Value Proposition

**As a** user
**I need** to filter a product by country
**to be able to** find the equivalent available to me
## Description

<img width="450" alt="Filter issue picture" src="https://user-images.githubusercontent.com/106099037/179222109-8989d8dc-e96b-4a5f-9d43-c36293407f66.png">

## Acceptance Criteria

- [x] I can select the country that I want the equivalent to be from by using a drop-down menu
- [x] The country that I want the equivalent to be from is included on the resulting card

## Tasks

(for developers team)

- [x] Add the corresponding countries to the existing db.js
- [x] Country filter function
- [x] Country drop-down menu
