### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by anresa** [anresa/capstone-project#3]
## Value Proposition

**As a** user
**I need** to navigate pages
**to be able to** visit all of them

## Description

<img width="350" alt="Navigation picture" src="https://user-images.githubusercontent.com/106099037/179765524-a80556e1-3f97-427d-968a-5b0f3cf56309.png">

## Acceptance Criteria

- [x] I can navigate between all pages by using the navigation bar at the bottom of each page
- [x] Clicking on an icon in the navigation bar brings me to the corresponding page
- [x] The icon for the Homepage is centered and bigger than the other icons
- [x] The icons are clear and easy to understand 

## Tasks

(for developers team)

- [x] Create the "add" page
- [x] Create the "categories" page
- [x] Create the "favorites" page
- [x] Create the "profile" page
- [x] Navigation function
- [x] Navigation icons
- [x] Styling
