### ISSUE TITLE
Save favorites

### ISSUE THREAD

**Issue by anresa** [anresa/capstone-project#4]
## Value Proposition

**As a** user
**I need** to save a favorite
**to be able to** remember it

## Description

<img width="450" alt="Favorites picture" src="https://user-images.githubusercontent.com/106099037/179764855-72c4d253-1974-466e-bf6a-101a82f29d0a.png">

## Acceptance Criteria

- [x] I can add a card to my favorites by clicking on the heart icon
- [x] Every favorite is saved as a different card
- [x] All saved cards appear on a separate page
- [x] Favorites can be removed/ unsaved by clicking the heart icon again 

## Tasks

(for developers team)

- [x] Favorites page
- [x] Bookmark/saving function
- [x] Heart icon
- [x] Styling
