### ISSUE TITLE
Add a new equivalent

### ISSUE THREAD

**Issue by anresa** [anresa/capstone-project#5]
## Value Proposition

**As a** user
**I need** an "add" card/page
**to be able to** add a new equivalent 

## Description

<img width="250" alt="Bildschirmfoto 2022-07-19 um 16 21 35" src="https://user-images.githubusercontent.com/106099037/179774640-299d5f84-99eb-47fc-8496-df96decfd306.png">

## Acceptance Criteria

- [x] I can type the product name into a text field
- [x] I can select the country the product is from by using a drop-down menu
- [x] I can type the equivalent  into a text field
- [x]  I can select the country the equivalent is from by using a drop-down menu
- [x]  After I selected a country its corresponding flag appears next to it (2)
- [x] I can add a picture of my product to the card
- [x] The new card is being added to the overall databank and can be found over the search function on the homepage
- [x] I can edit the card later if I want to change something by using the edit button

## Tasks

(for developers team)

- [x] Create "add" card
- [x] Product text field
- [x] Equivilant text field
- [x] Country text field (2)
- [x] Country drop-down menus (2)
- [x] Implement the county flag images
- [x] Add picture function
- [x] Placeholder picture for pictureless cards
- [x] Styling
